In [2]:
import numpy as np

In [6]:
x_shape = (2, 3, 4, 4)
w_shape = (3, 3, 4, 4)
x = np.linspace(-0.1, 0.5, num=np.prod(x_shape)).reshape(x_shape)
w = np.linspace(-0.2, 0.3, num=np.prod(w_shape)).reshape(w_shape)


In [7]:
?np.broadcast_arrays

In [10]:
np.zeros_like(x)

array([[[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]]]])

In [84]:
from cs231n.im2col import *

In [85]:
im2col(x)

NameError: name 'im2col' is not defined

In [64]:
np.shape(np.pad(x,((0,0),(0,0),(1,1),(1,1)),'constant'))

(2, 3, 6, 6)

In [63]:
?np.pad

In [55]:
bn_params = [{'mode': 'train'} for i in xrange(6 - 1)]

In [15]:
bn_params[0]

{'mode': 'train'}

In [46]:
a= np.ones([5,4])

In [53]:
np.pad(a,2,'constant')

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [36]:
p=0.1

In [37]:
nm=np.random.rand(*a.shape)<p

In [38]:
nm

array([[False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]], dtype=bool)

In [39]:
a *= nm

In [40]:
a

array([[ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [17]:
mode = 'train'
for k in bn_params:
    k[mode] = mode

In [18]:
for k in bn_params:
    print k

{'train': 'train', 'mode': 'train'}
{'train': 'train', 'mode': 'train'}
{'train': 'train', 'mode': 'train'}
{'train': 'train', 'mode': 'train'}
{'train': 'train', 'mode': 'train'}


In [3]:
c=np.ones([2,3])

In [4]:
np.ones_like(c)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [9]:
f=np.zeros((10,5,5))

In [16]:
f.reshape((f.shape[0],-1))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
      

In [3]:
f=np.zeros((10,5))

In [7]:
np.dot(f, np.transpose(f)).reshape(np.shape(g))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [9]:
g=np.zeros((4,4))+np.ones((1,4))

In [10]:
g

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [12]:
dx,dy=1,\
2

In [25]:
a=np.ones((1,4))

In [26]:
a>0

array([[ True,  True,  True,  True]], dtype=bool)

In [58]:
a=np.array([[ 1.,  3.,  3.]]).reshape(-1)



In [59]:
np.shape(a)

(3,)

In [49]:
import random

In [60]:
x=np.random.rand(3,4)

In [61]:
x

array([[ 0.8765292 ,  0.49245263,  0.44421397,  0.33443783],
       [ 0.50741806,  0.93321114,  0.27771314,  0.33449503],
       [ 0.4895372 ,  0.01017714,  0.41290159,  0.23632245]])

In [62]:
x[np.arange(3), a.astype(int)]

array([ 0.49245263,  0.33449503,  0.23632245])

In [55]:
a.astype(int)


array([[1],
       [3],
       [3]])

In [56]:
np.arange(3)

array([0, 1, 2])

In [57]:
x[[0, 1, 2],[2,1,3]]

array([ 0.31214457,  0.99598316,  0.6090076 ])

In [68]:
layer_out={}

In [73]:
layer_out[2]=22


In [76]:
layer_out.keys()

[1, 2]

In [77]:
range(5)[::-1]

[4, 3, 2, 1, 0]

In [78]:
x=np.random.rand(3,4)

In [79]:
x*x

array([[ 0.67513191,  0.66331426,  0.06260628,  0.43927879],
       [ 0.86371704,  0.2947191 ,  0.42121544,  0.01468696],
       [ 0.08144191,  0.0388631 ,  0.01119002,  0.53583341]])

In [80]:
x

array([[ 0.82166411,  0.81444107,  0.25021248,  0.6627811 ],
       [ 0.92936378,  0.54288037,  0.64901113,  0.12118977],
       [ 0.28538029,  0.19713727,  0.10578287,  0.73200643]])

In [81]:
np.sqrt(x)

array([[ 0.9064569 ,  0.90246389,  0.50021243,  0.81411369],
       [ 0.96403516,  0.73680416,  0.80561227,  0.34812321],
       [ 0.53420997,  0.44400143,  0.32524278,  0.85557374]])

In [82]:
x/x

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [2]:
x=np.random.rand(3,4)

In [4]:
np.sum(x,axis=1)

array([ 1.22628924,  1.7529675 ,  3.03888511])

In [18]:
np.mean(x, axis=0)

array([ 0.31773088,  0.59007365,  0.43022516,  0.28069731])

In [10]:
x

array([[ 0.58162427,  0.46304439,  0.44321672,  0.6050424 ],
       [ 0.30734239,  0.85429861,  0.51158377,  0.23190826],
       [ 0.06422597,  0.45287794,  0.335875  ,  0.00514128]])

In [13]:
np.sqrt(np.var(x, axis=1))

array([ 0.07093587,  0.2410404 ,  0.18572109])

In [20]:
y=(x-np.mean(x, axis=0))/np.sqrt(np.var(x, axis=0))

In [22]:
np.var(y,axis=0)

array([ 1.,  1.,  1.,  1.])

In [6]:
x

array([[ 0.09771418,  0.66312514,  0.1644051 ,  0.30104482],
       [ 0.61643963,  0.23069571,  0.62610675,  0.2797254 ],
       [ 0.38266014,  0.93261905,  0.82338151,  0.90022441]])

In [7]:
(np.var(x, axis=0))

array([ 0.04499146,  0.08359095,  0.07625952,  0.08272108])

In [8]:
(np.mean(x, axis=0))

array([ 0.36560465,  0.6088133 ,  0.53796445,  0.49366488])